# CLI to query engine and family: aws rds describe-db-engine-versions, Select appropriate family and engine version

# engine: # 'sqlserver-ee' | 'sqlserver-se' | 'sqlserver-ex' | 'sqlserver-web'
# engine_version: '11.xx' | '12.xx' | '13.xx' | '14.xx'
# family: {engine}-11.0 | {engine}-12.0 | {engine}-13.0 | {engine}-14.0

#dns_record: mssql

#deletion_policy: Snapshot

# parameters:
#   authentication_timeout: '60'

master_login:
  username_ssm_param: /rds/RDS_MASTER_USERNAME
  password_ssm_param: /rds/RDS_MASTER_PASSWORD

publicly_accessible: false

# Specify a specific collation for the mssql server. Default is SQL_Latin1_General_CP1_CI_AS
# character_set: SQL_Latin1_General_CP1_CI_A

# You are able to specify ips and security groups to be added to the rule.
# security_group_rules:
#   - ip: 0.0.0.0/0
#     desc: Public access
#   - security_group_id: sg-1234567
#     desc: My security group

storage_encrypted: false
#kms_key_id: arn:aws:kms:ap-southeast-2:111111111111:key/12345678-1234-1234-1234-111111111111

#Set to true to enable the mssql option to backup/restore from backup files in an S3 bucket
#Pass the bucket name to the component with the DatabaseBucket parameter
#native_backup_restore: false

#Sometimes required to be specified for configurations with options enabled
#license_model: license-included | bring-your-own-license | general-public-license

#
#maintenance_window:

#The daily time range during which automated backups are created if automated backups are enabled,
#backup_window: